package com.dev.aes.constant;

public enum NotificationType {
    FOLDER_CREATED, FOLDER_DELETED, FOLDERS_FILES_MOVED, UPLOAD, OCR, FILE_CLASSIFICATION_CONFIRMED, DETECTION,
    DATA_ENTERED, DATA_CONFIRMED, ERROR_DETECTED, ERROR_DETECTION_FINISHED, ENQUEUE_ERROR
}
